/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperinvestorsIndexRouteImport } from './routes/superinvestors/index'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as SuperinvestorsCikRouteImport } from './routes/superinvestors/$cik'
import { Route as AssetsCodeRouteImport } from './routes/assets/$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperinvestorsIndexRoute = SuperinvestorsIndexRouteImport.update({
  id: '/superinvestors/',
  path: '/superinvestors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperinvestorsCikRoute = SuperinvestorsCikRouteImport.update({
  id: '/superinvestors/$cik',
  path: '/superinvestors/$cik',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsCodeRoute = AssetsCodeRouteImport.update({
  id: '/assets/$code',
  path: '/assets/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets/$code': typeof AssetsCodeRoute
  '/superinvestors/$cik': typeof SuperinvestorsCikRoute
  '/assets': typeof AssetsIndexRoute
  '/superinvestors': typeof SuperinvestorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets/$code': typeof AssetsCodeRoute
  '/superinvestors/$cik': typeof SuperinvestorsCikRoute
  '/assets': typeof AssetsIndexRoute
  '/superinvestors': typeof SuperinvestorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets/$code': typeof AssetsCodeRoute
  '/superinvestors/$cik': typeof SuperinvestorsCikRoute
  '/assets/': typeof AssetsIndexRoute
  '/superinvestors/': typeof SuperinvestorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets/$code'
    | '/superinvestors/$cik'
    | '/assets'
    | '/superinvestors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets/$code'
    | '/superinvestors/$cik'
    | '/assets'
    | '/superinvestors'
  id:
    | '__root__'
    | '/'
    | '/assets/$code'
    | '/superinvestors/$cik'
    | '/assets/'
    | '/superinvestors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsCodeRoute: typeof AssetsCodeRoute
  SuperinvestorsCikRoute: typeof SuperinvestorsCikRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  SuperinvestorsIndexRoute: typeof SuperinvestorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superinvestors/': {
      id: '/superinvestors/'
      path: '/superinvestors'
      fullPath: '/superinvestors'
      preLoaderRoute: typeof SuperinvestorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superinvestors/$cik': {
      id: '/superinvestors/$cik'
      path: '/superinvestors/$cik'
      fullPath: '/superinvestors/$cik'
      preLoaderRoute: typeof SuperinvestorsCikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$code': {
      id: '/assets/$code'
      path: '/assets/$code'
      fullPath: '/assets/$code'
      preLoaderRoute: typeof AssetsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsCodeRoute: AssetsCodeRoute,
  SuperinvestorsCikRoute: SuperinvestorsCikRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  SuperinvestorsIndexRoute: SuperinvestorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
